core/core/urls.py
from django.urls import include, path

from core.admin import admin_site

urlpatterns = [
    path("admin-natalshopping/", admin_site.urls),
    path("", include("meetlink.urls")),
]

core/meetlink/urls.py
from django.urls import include, path
from meetlink.domain.call import call_view
from meetlink.domain.superadmin import superadmin_view
from rest_framework.routers import SimpleRouter

from . import views

router = SimpleRouter()

router.register("calls", call_view.CallAPI, basename="calls")

urlpatterns = [
    path("", views.index, name="index"),
    path("totem/", views.totem, name="totem"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("calls/", call_view.calls_index, name="calls_index"),
    path(
        "calls/<int:id>/in_progress/",
        call_view.call_in_progress,
        name="call_in_progress",
    ),
    path("calls/<int:id>", call_view.CallsEdit.as_view(), name="calls_edit"),
    path("api/", include(router.urls)),
    path("create_call/", call_view.create_call, name="create_call"),
    path("superadmin/actions/", superadmin_view.actions, name="create_call"),
    # path("create-superuser/", views.create_superuser, name="create_superuser"),
]

core/meetlink/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models

# Create your models here.


class Role(models.TextChoices):
    SUPERADMIN = "SUPERADMIN", "Super Administrador"
    MANAGER = "MANAGER", "Gestor"
    TOTEM = "TOTEM", "Totem"
    INTERPRETER = "INTERPRETER", "Intérprete"

    class Meta:
        verbose_name = "Permissão"
        verbose_name_plural = "Permissões"


class User(AbstractUser):
    role = models.CharField(
        max_length=20,
        choices=Role.choices,
        default=Role.MANAGER,
        verbose_name="Permissão",
    )

    groups = models.ManyToManyField(
        Group,
        related_name="custom_user_set",
        blank=True,
    )

    user_permissions = models.ManyToManyField(
        Permission,
        related_name="custom_user_permissions_set",
        blank=True,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Subject(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nome")
    description = models.TextField(blank=True, null=True, verbose_name="Descrição")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Assunto"
        verbose_name_plural = "Assuntos"


class Call(models.Model):
    responsible = models.ForeignKey(
        "User",
        on_delete=models.CASCADE,
        related_name="responsible_calls",
        blank=True,
        null=True,
        verbose_name="Responsável",
    )
    interpreter = models.ForeignKey(
        "User",
        on_delete=models.CASCADE,
        related_name="interpreter_calls",
        blank=True,
        null=True,
        verbose_name="Interprete",
    )
    subject = models.ForeignKey(
        "Subject",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Assunto",
    )
    description = models.TextField(verbose_name="Descrição", blank=True, null=True)
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Hora Solicitação"
    )
    manager_entered_at = models.DateTimeField(
        verbose_name="Hora de Entrada do Gestor", blank=True, null=True
    )
    interpreter_entered_at = models.DateTimeField(
        verbose_name="Hora de Entrada do Intérprete", blank=True, null=True
    )
    updated_at = models.DateTimeField(
        verbose_name="Hora Atualização", blank=True, null=True
    )
    finished_at = models.DateTimeField(
        verbose_name="Hora Finalização", blank=True, null=True
    )

    def __str__(self):
        return (
            f"Call by {self.responsible.username if self.responsible else None}"
            f" at {self.created_at}"
        )

    class Meta:
        verbose_name = "Chamada"
        verbose_name_plural = "Chamadas"

core/meetlink/forms.py
from django import forms


class LoginForm(forms.Form):
    email = forms.EmailField(
        required=True,
        error_messages={
            "required": "O campo email é obrigatório.",
            "invalid": "Insira um email válido.",
        },
    )
    password = forms.CharField(
        widget=forms.PasswordInput,
        required=True,
        error_messages={"required": "O campo senha é obrigatório."},
    )


class EditCallForm(forms.Form):
    description = forms.CharField(
        max_length=500,
        required=False,
        error_messages={"max_length": "Máximo de 500 caracteres"},
    )
    subject = forms.CharField(required=False)

core/meetlink/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views import View

from .domain.user.user_exceptions import (
    LoginDataIsInvalidException,
    UserEmailOrPasswordIsInvalidException,
)
from .forms import LoginForm
from .models import Role, User

# Create your views here.


@login_required
def index(request):
    user: User = request.user

    if user.role in (Role.SUPERADMIN, Role.MANAGER, Role.INTERPRETER):
        return redirect("dashboard")

    return redirect("totem")


@login_required
def totem(request):
    user: User = request.user

    if user.role in (Role.MANAGER, Role.INTERPRETER):
        return redirect("dashboard")

    return render(
        request, "totem.html", {"user": user, "hide_sidebar": True, "screen_dark": True}
    )


@login_required
def dashboard(request):
    user = request.user

    return render(request, "dashboard.html", {"user": user})


class LoginView(View):
    def get(self, request):
        return render(request, "login.html", {"hide_sidebar": True})

    def post(self, request):
        try:
            data = LoginForm(request.POST)

            if not data.is_valid():
                raise LoginDataIsInvalidException()

            user = User.objects.get(email=data.cleaned_data["email"])

            if not check_password(data.cleaned_data["password"], user.password):
                raise UserEmailOrPasswordIsInvalidException()

            login(request, user)

            return redirect("index")

        except User.DoesNotExist:
            return render(
                request,
                "login.html",
                {"hide_sidebar": True, "error": "Usuário não encontrado"},
            )

        except Exception as e:
            print(e)
            return render(
                request, "login.html", {"hide_sidebar": True, "error": e.__str__}
            )


def logout_view(request):
    user = request.user

    if user:
        logout(request)

    return redirect("index")


def create_superuser(request):
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser("admin", "shopping@admin.com", "123456")
        return HttpResponse(
            "Super usuário criado com email shopping@admin.com e senha 123456!"
        )
    else:
        return HttpResponse("Superuser already exists.")

core/meetlink/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        Acesse MeetLink - NatalShopping | {% block title %}Defina um título para
        sua página{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/_base.css' %}" />
    {% block head %}{% endblock %}
</head>

<body class="{% if screen_dark %}bg-secondary-color{% endif %}">
    {% if not hide_sidebar %} {% include '_sidebar.html' %} {% endif %}

    <main class="main {% if not hide_sidebar %}md:ml-108{% endif %}">
        {% block main %}
        <p>Carregue o bloco 'main'</p>
        {% endblock %}
    </main>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
</body>

</html>

core/meetlink/templates/_sidebar.html
{% load static %}
<aside class="sidebar shadow-lg p-12 flex-column align-items-center fixed-top">
    <ul class="d-flex flex-column gap-1 h-100">
        <li class="py-12">
            <a href="/">
                <img class="w-72" src="{% static 'img/natal_shopping_logo_white.jpg' %}"
                    alt="Natal shopping logo ciano" />
            </a>
        </li>
        <li class="d-flex">
            <a class="rounded-2 w-100 h-100 p-3 text-primary-color hover:text-white hover:bg-primary-color {% if request.path == '/dashboard/' %}text-white bg-primary-color{% endif %}"
                href="/dashboard">
                Gestão
            </a>
        </li>
        <li class="d-flex">
            <a class="rounded-2 w-100 h-100 p-3 text-primary-color hover:text-white hover:bg-primary-color {% if request.path == '/calls/' %}text-white bg-primary-color{% endif %}"
                href="/calls/?page=1&per_page=10">
                Histórico de chamadas
            </a>
        </li>
        {% if SHOULD_VIEW_TOTEM_REDIRECT %}
        <li class="d-flex">
            <a class="rounded-2 w-100 h-100 p-3 text-primary-color hover:text-white hover:bg-primary-color {% if request.path == '/totem/' %}text-white bg-primary-color{% endif %}"
                href="/totem">
                Tela do totem
            </a>
        </li>
        {% endif %}
        {% if SHOUD_VIEW_SUPERADMIN_REDIRECT %}
        <li class="d-flex">
            <a class="rounded-2 w-100 h-100 p-3 text-primary-color hover:text-white hover:bg-primary-color {% if request.path == '/superadmin/actions/' %}text-white bg-primary-color{% endif %}"
                href="/superadmin/actions/">
                Administrador
            </a>
        </li>
        {% endif %}
        <li class="d-flex mt-auto">
            <a class="rounded-2 w-100 h-100 p-3 text-primary-color hover:text-white hover:bg-primary-color {% if request.path == '/logout' %}text-white bg-primary-color{% endif %}"
                href="/logout">
                Sair
            </a>
        </li>
    </ul>
</aside>

core/meetlink/templates/calls/edit.html
{% extends '_base.html' %}

{% block title %}Editar dados da chamada {{ call.id }}{% endblock %}

{% load static %}

{% block main %}

<h1 class="mb-5">Atendimento #{{ call.id }} | {{ call.responsible }} | {{ call.created_at|date:"d/m/Y" }}</h1>

{% if error %}
<div class="p-3 mb-3 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3">
    {{ error }}
</div>
{% endif %}

{% if success %}
<div class="p-3 mb-3 text-success-emphasis bg-success-subtle border border-success-subtle rounded-3">
    {{ success }}
</div>
{% endif %}



<form action="/calls/{{ call.id }}" method="POST">
    {% csrf_token %}

    <div class="mb-3 d-flex flex-column">
        <label for="description" class="form-label">Descrição</label>
        {% if CANNOT_EDIT_CALL %}
        <textarea type="text" name="description" id="description" class="form-control"
            disabled>{{ call.description }}</textarea>
        {% else %}
        <textarea type="text" name="description" id="description" class="form-control">{{ call.description }}</textarea>
        {% endif %}

    </div>

    <div class="mb-3 d-flex flex-column">
        <label for="subject" class="form-label">Assunto</label>
        {% if CANNOT_EDIT_CALL %}
        <select id="subject" name="subject" class="form-select" disabled>
            <option value="">------ Sem assunto ------</option>
            {% for subject in subjects %}

            {% if subject == call.subject %}
            <option value="{{ subject.id }}" selected>{{ subject.name }}</option>
            {% else %}
            <option value="{{ subject.id }}">{{ subject.name }}</option>
            {% endif %}

            {% endfor %}
        </select>
        {% else %}
        <select id="subject" name="subject" class="form-select">
            <option value="">------ Sem assunto ------</option>
            {% for subject in subjects %}

            {% if subject == call.subject %}
            <option value="{{ subject.id }}" selected>{{ subject.name }}</option>
            {% else %}
            <option value="{{ subject.id }}">{{ subject.name }}</option>
            {% endif %}

            {% endfor %}
        </select>
        {% endif %}
    </div>

    {% if CANNOT_EDIT_CALL %}
    <button class="btn btn-primary" type="submit" disabled>Confirmar</button>
    {% else %}
    <button class="btn btn-primary" type="submit">Confirmar</button>
    {% endif %}
</form>

{% endblock %}

core/meetlink/templates/calls/in_progress.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        Acesse MeetLink - Chamada {{ call.id }} em andamento
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/_base.css' %}" />
</head>

<body class="d-flex w-100 h-100 bg-dark-blue">
    <div class="p-16 w-100">
        <div data-js="video-container" class="video-container d-grid gap-4 mb-4">
            <video data-js="video-local" autoplay muted class="video-item-large rounded placeholder"></video>
        </div>

        <div class="d-flex justify-content-center gap-4">
            <button data-js="video-finish-call-button" class="btn btn-secondary">Finalizar chamada</button>
        </div>

        <input type="hidden" data-js="user-role" value="{{ user.role }}">
        <input type="hidden" data-js="user-id" value="{{ user.id }}">
        <input type="hidden" data-js="call-id" value="{{ call.id }}">
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/call.js' %}"></script>
</body>

</html>

core/meetlink/templates/calls/index.html
{% extends '_base.html' %}

{% block title %}Histórico de chamadas{% endblock %}

{% load static %}

{% block main %}

<h1 class="mb-5">Histórico de chamadas</h1>

{% if paginated_calls %}
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Responsável</th>
            <th>Intérprete</th>
            <th>Assunto</th>
            <th>Início</th>
            <th>Fim</th>
            <th>Visualizar</th>
        </tr>
    </thead>

    <tbody>
        {% for call in paginated_calls %}
        <tr>
            <td>Atendimento #{{ call.id }} - {{ call.created_at|date:"d/m/Y" }}</td>
            <td>
                {% if call.responsible %}
                <span class="p-1 text-success-emphasis bg-success-subtle border border-success-subtle rounded-3">
                    {{ call.responsible }}
                </span>
                {% else %}
                <span class="p-1 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3">
                    Chamada perdida
                </span>
                {% endif %}
            </td>
            <td>
                {% if call.interpreter %}
                <span class="p-1 text-success-emphasis bg-success-subtle border border-success-subtle rounded-3">
                    {{ call.interpreter }}
                </span>
                {% else %}
                -
                {% endif %}
            </td>
            <td>{% if call.subject %}
                {{ call.subject }}
                {% else %}
                -
                {% endif %}
            </td>
            <td>{{ call.created_at|time:"H:i" }}</td>
            <td>{{ call.finished_at|time:"H:i" }}</td>
            <td><a class="btn btn-primary" href="/calls/{{ call.id }}">Visualizar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
        {% if paginated_calls.has_previous %}
        <a href="?page=1&per_page={{ query.per_page }}">&laquo; primeira</a>
        <a href="?page={{ paginated_calls.previous_page_number }}&per_page={{ query.per_page }}">anterior</a>
        {% endif %}

        <span class="current">
            Página {{ paginated_calls.number }} de {{ paginated_calls.paginator.num_pages }}.
        </span>

        {% if paginated_calls.has_next %}
        <a href="?page={{ paginated_calls.next_page_number }}&per_page={{ query.per_page }}">próxima</a>
        <a href="?page={{ paginated_calls.paginator.num_pages }}&per_page={{ query.per_page }}">última &raquo;</a>
        {% endif %}
    </span>

    <div class="mb-3">
        Itens por página:
        <a href="?per_page=10&page=1" class="{% if per_page == 25 %}font-weight-bold{% endif %}">10</a> |
        <a href="?per_page=25&page=1" class="{% if per_page == 50 %}font-weight-bold{% endif %}">25</a> |
        <a href="?per_page=50&page=1" class="{% if per_page == 100 %}font-weight-bold{% endif %}">50</a>
    </div>
</div>

{% else %}
<p>As chamadas do sistema ficam registradas aqui. Sem chamadas no momento.</p>
{% endif %}

{% endblock %}

core/meetlink/templates/create_call.html
<!DOCTYPE html>
<html>

<head>
    <title>WebRTC Video Call</title>
</head>

<body>
    <video id="localVideo" autoplay muted></video>
    <video id="remoteVideo" autoplay></video>
    <button id="startCallButton">Start Call</button>
    <button id="endCallButton">End Call</button>
</body>

</html>

core/meetlink/templates/dashboard.html
{% extends '_base.html' %}

{% block title %}Dashboard{% endblock %}

{% load static %}

{% block main %}

<h1 class="mb-5">Início - {{ user.get_role_display }}</h1>

<button class="p-12 rounded-3 btn btn-primary" data-js="manager-enter-call-button" disabled>
    Ainda sem chamadas
</button>

<audio data-js="audio-phone-ring" src="{% static '/aud/ring_phone.wav' %}"></audio>

<input type="hidden" data-js="user-id" value="{{ user.id }}">
<input type="hidden" data-js="user-role" value="{{ user.role }}">

{% block scripts %}
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

{% endblock %}

core/meetlink/templates/login.html
{% extends '_base.html' %}

{% load static %}

{% block main %}
<div class="d-flex flex-column align-items-center gap-4">
    <img class="w-48" src="{% static 'img/natal_shopping_logo_white.jpg' %}" alt="Natal shopping logo ciano">

    <h1>Faça login</h1>

    <form class="login__form d-flex flex-column gap-4 w-100" method="POST">
        {% csrf_token %}
        <div>
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name="email">
        </div>

        <div>
            <label for="password" class="form-label">Senha</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>

        {% if error %}
        <div class="p-3 mb-3 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3">
            {{ error }}
        </div>
        {% endif %}

        <button type="submit" class="btn btn-primary">Confirmar</button>
    </form>
</div>

{% endblock %}

core/meetlink/templates/superadmin/actions.html
{% extends '_base.html' %}

{% block title %}Tela do Superadmin{% endblock %}

{% load static %}

{% block main %}

<h1 class="mb-5">Tela de Administrador</h1>

{% if not call.finished_at %}
<button class="p-12 rounded-3 btn btn-primary" data-js="admin-end-call-button">
    Finalize a chamada {{ call.id }}
</button>
{% else %}
<button class="p-12 rounded-3 btn btn-primary" disabled>
    Sem chamdas em andamento
</button>
{% endif %}

<input type="hidden" data-js="user-id" value="{{ user.id }}">
<input type="hidden" data-js="user-role" value="{{ user.role }}">
<input type="hidden" data-js="call-id" value="{{ call.id }}">

{% endblock %}

core/meetlink/templates/totem.html
{% extends '_base.html' %}

{% load static %}

{% block head %}
<meta http-equiv="refresh" content="300">
{% endblock %}

{% block main %}

<div class="d-flex flex-column justify-content-center align-items-center h-100 p-2">
    <img class="w-72 pb-12" src="{% static 'img/natal_shopping_logo_cyan.jpg' %}" alt="Natal shopping logo ciano" />

    <h1 class="text-uppercase fs-1 text-white fw-bold">Precisa de ajuda?</h1>

    <p class="text-uppercase text-center fs-3 pb-12 text-color-light-grey">Selecione a opção para ser atendido por nossa
        equipe de
        suporte</p>

    <div class="d-flex gap-4 w-100 justify-content-center" data-js="buttons-container">
        <button class="p-8 md:p-16 rounded-3 btn btn-primary" data-js="request-call-button">
            Atendimento em Português
        </button>

        <button class="p-8 md:p-16 rounded-3 btn btn-primary" data-js="request-interpreter-call-button">
            Atendimento em Libras
        </button>
    </div>

    <button class="mt-6 p-8 md:p-16 rounded-3 btn btn-secondary" data-js="accessibility-button">Acessibilidade</button>
</div>

<input type="hidden" data-js="user-id" value="{{ user.id }}">
<input type="hidden" data-js="user-role" value="{{ user.role }}">

{% block scripts %}
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

{% endblock %}